### ISSUE TITLE
Crash while opening a file

### ISSUE THREAD

**Issue by jnko** [harbaum/upide#11]
upide git main branch
python-pyqt5 5.15.6-7
python-pyserial 3.5-4

Opening a file from esp32 results in crash.
```
Traceback (most recent call last):
  File "/home/USER/upide/src/editor.py", line 409, in paintEvent
    self.editor.lineNumberAreaPaintEvent(event)
  File "/home/USER/upide/src/editor.py", line 694, in lineNumberAreaPaintEvent
    painter.drawText(0, top, self.lineNumberArea.width()-2, height,
TypeError: arguments did not match any overloaded call:
  drawText(self, Union[QPointF, QPoint], str): argument 1 has unexpected type 'int'
  drawText(self, QRectF, int, str): argument 1 has unexpected type 'int'
  drawText(self, QRect, int, str): argument 1 has unexpected type 'int'
  drawText(self, QRectF, str, option: QTextOption = QTextOption()): argument 1 has unexpected type 'int'
  drawText(self, QPoint, str): argument 1 has unexpected type 'int'
  drawText(self, int, int, int, int, int, str): argument 2 has unexpected type 'float'
  drawText(self, int, int, str): argument 2 has unexpected type 'float'
fish: Job 1, './upide.py' terminated by signal SIGABRT (Abort)
```

![grafik](https://user-images.githubusercontent.com/2241599/166628460-f4f15b64-95ea-4b87-aa79-449da1abea96.png)

Anyway nice approach!
Just another hint: It would be great if we could use the repl/interactive mode and the editor simultaneously.

**Comment by harbaum** [comment]
Thanks for the report. I just checked an attempt to fix into master. Please try again.

**Comment by harbaum** [comment]
> Anyway nice approach! Just another hint: It would be great if we could use the repl/interactive mode and the editor simultaneously.

The editor itself is working. But you cannot save or run files or open new ones. That isn't possible as when using repl the user takes over full control of the board. Thus upide cannot talk to the board itself during that time and is unable to load or save files.

**Comment by jnko** [comment]
> Thanks for the report. I just checked an attempt to fix into master. Please try again.

No, sorry still the same issue.
```
Examples local exception: [Errno 2] No such file or directory: '/home/USER/upide/src/examples/index.xml'
Traceback (most recent call last):
  File "/home/USER/upide/src/editor.py", line 409, in paintEvent
    self.editor.lineNumberAreaPaintEvent(event)
  File "/home/USER/upide/src/editor.py", line 694, in lineNumberAreaPaintEvent
    painter.drawText(0, top, self.lineNumberArea.width()-2, height,
TypeError: arguments did not match any overloaded call:
  drawText(self, Union[QPointF, QPoint], str): argument 1 has unexpected type 'int'
  drawText(self, QRectF, int, str): argument 1 has unexpected type 'int'
  drawText(self, QRect, int, str): argument 1 has unexpected type 'int'
  drawText(self, QRectF, str, option: QTextOption = QTextOption()): argument 1 has unexpected type 'int'
  drawText(self, QPoint, str): argument 1 has unexpected type 'int'
  drawText(self, int, int, int, int, int, str): argument 2 has unexpected type 'float'
  drawText(self, int, int, str): argument 2 has unexpected type 'float'
fish: Job 1, './upide.py' terminated by signal SIGABRT (Abort)
```

**Comment by harbaum** [comment]
It's a little hard to debug without being able to reproduce the problem.

I committed another attempt. Please retry.

**Comment by jnko** [comment]
Now it works, thanks a lot.
